### PR TITLE
refactor: improvements

### PR DESCRIPTION
**Pull request by NikanWasTaken**

### CODE REVIEW

**Comment by NikanWasTaken** [comment]
@fb-sean would you mind reviewing the pull request?

**Review by fb-sean — COMMENTED** [review]
Yeah looks good

**Review by fb-sean — COMMENTED** [review]
Yes all looks fine

**Review by fb-sean — COMMENTED** [review]
So I reviewed all files I didnt find any other typo

**Comment by NikanWasTaken** [comment]
Aight, sweet! You can now merge the pull request.

**Pull request merged**
